### ISSUE TITLE
This bundle is invalid. The bundle at path Payload/projectName.app/Frameworks/BNBSdkApi.framework has an invalid CFBundleIdentifier 'banuba.sdk.sdk_api'

### ISSUE THREAD

**Issue by ChurikiTenna** [Banuba/BanubaSDK-iOS#2]
Hi, thank you for the great sdk!

I'm using Banuba sdk via cocoapods.
When I try to archive the project, it fails with 'This bundle is invalid' error.

Full error message:
`This bundle is invalid. The bundle at path Payload/projectName.app/Frameworks/BNBSdkApi.framework has an invalid CFBundleIdentifier 'banuba.sdk.sdk_api' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'banuba.sdk.sdk\u005fapi' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105] With error code STATE_ERROR.VALIDATION_ERROR.90049 for id ea662143-ace7-418e-95e7-e72119f57bc9`

Podfile:
`pod 'BanubaSdk', '1.4.0'`

Am I not supposed to install sdk with cocoapods? Or am I doing something wrong?
Thank you for your time.

**Comment by ghost** [comment]
Hi @ChurikiTenna I'm experiencing the same issue. How did you solved it?
